<?php

namespace Database\Seeders;

use App\Models\Device;
use Illuminate\Database\Seeder;

class DeviceSeeder extends Seeder
{
    public function run(): void
    {
        $devices = [
            [
                'brand' => 'Apple',
                'model_name' => 'iPhone 16 Pro Max',
                'slug' => 'apple-iphone-16-pro-max',
                'image_url' => 'https://images.unsplash.com/photo-1722426920707-6d7f0ab0f7cf?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '4685mAh',
                'camera' => '48MP main + 48MP ultrawide + 12MP telephoto',
                'storage' => '256GB / 512GB / 1TB',
                'ram' => '8GB',
                'processor' => 'Apple A18 Pro',
                'performance' => 'Flagship',
                'display' => '6.9-inch LTPO OLED 120Hz',
                'operating_system' => 'iOS 18',
            ],
            [
                'brand' => 'Apple',
                'model_name' => 'iPhone 15 Pro',
                'slug' => 'apple-iphone-15-pro',
                'image_url' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2023,
                'battery' => '3274mAh',
                'camera' => '48MP main + 12MP ultrawide + 12MP telephoto',
                'storage' => '128GB / 256GB / 512GB / 1TB',
                'ram' => '8GB',
                'processor' => 'Apple A17 Pro',
                'performance' => 'Flagship',
                'display' => '6.1-inch LTPO OLED 120Hz',
                'operating_system' => 'iOS 17',
            ],
            [
                'brand' => 'Apple',
                'model_name' => 'iPhone 14',
                'slug' => 'apple-iphone-14',
                'image_url' => 'https://images.unsplash.com/photo-1663495991730-2d4d5b0a6c73?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2022,
                'battery' => '3279mAh',
                'camera' => '12MP main + 12MP ultrawide',
                'storage' => '128GB / 256GB / 512GB',
                'ram' => '6GB',
                'processor' => 'Apple A15 Bionic',
                'performance' => 'High-end',
                'display' => '6.1-inch Super Retina XDR OLED',
                'operating_system' => 'iOS 16',
            ],
            [
                'brand' => 'Samsung',
                'model_name' => 'Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'image_url' => 'https://images.unsplash.com/photo-1706275397080-6dbed9bf7178?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5000mAh',
                'camera' => '200MP main + 12MP ultrawide + 50MP telephoto + 10MP telephoto',
                'storage' => '256GB / 512GB / 1TB',
                'ram' => '12GB',
                'processor' => 'Snapdragon 8 Gen 3',
                'performance' => 'Flagship',
                'display' => '6.8-inch Dynamic AMOLED 2X 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Samsung',
                'model_name' => 'Galaxy S24',
                'slug' => 'samsung-galaxy-s24',
                'image_url' => 'https://images.unsplash.com/photo-1706744851344-4ebf1f4d1bdc?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '4000mAh',
                'camera' => '50MP main + 12MP ultrawide + 10MP telephoto',
                'storage' => '128GB / 256GB / 512GB',
                'ram' => '8GB',
                'processor' => 'Snapdragon 8 Gen 3',
                'performance' => 'Flagship',
                'display' => '6.2-inch Dynamic AMOLED 2X 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Samsung',
                'model_name' => 'Galaxy A55',
                'slug' => 'samsung-galaxy-a55',
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5000mAh',
                'camera' => '50MP main + 12MP ultrawide + 5MP macro',
                'storage' => '128GB / 256GB',
                'ram' => '8GB / 12GB',
                'processor' => 'Exynos 1480',
                'performance' => 'Mid-range',
                'display' => '6.6-inch Super AMOLED 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Xiaomi',
                'model_name' => 'Xiaomi 14',
                'slug' => 'xiaomi-14',
                'image_url' => 'https://images.unsplash.com/photo-1605236453806-6ff36851218d?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '4610mAh',
                'camera' => '50MP main + 50MP ultrawide + 50MP telephoto',
                'storage' => '256GB / 512GB',
                'ram' => '12GB / 16GB',
                'processor' => 'Snapdragon 8 Gen 3',
                'performance' => 'Flagship',
                'display' => '6.36-inch LTPO AMOLED 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Xiaomi',
                'model_name' => '13T Pro',
                'slug' => 'xiaomi-13t-pro',
                'image_url' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2023,
                'battery' => '5000mAh',
                'camera' => '50MP main + 12MP ultrawide + 50MP telephoto',
                'storage' => '256GB / 512GB / 1TB',
                'ram' => '12GB / 16GB',
                'processor' => 'Dimensity 9200+',
                'performance' => 'High-end',
                'display' => '6.67-inch AMOLED 144Hz',
                'operating_system' => 'Android 13',
            ],
            [
                'brand' => 'Xiaomi',
                'model_name' => 'Redmi Note 13 Pro Plus',
                'slug' => 'xiaomi-redmi-note-13-pro-plus',
                'image_url' => 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5000mAh',
                'camera' => '200MP main + 8MP ultrawide + 2MP macro',
                'storage' => '256GB / 512GB',
                'ram' => '8GB / 12GB / 16GB',
                'processor' => 'Dimensity 7200 Ultra',
                'performance' => 'Upper mid-range',
                'display' => '6.67-inch AMOLED 120Hz',
                'operating_system' => 'Android 13',
            ],
            [
                'brand' => 'Google',
                'model_name' => 'Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'image_url' => 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2023,
                'battery' => '5050mAh',
                'camera' => '50MP main + 48MP ultrawide + 48MP telephoto',
                'storage' => '128GB / 256GB / 512GB / 1TB',
                'ram' => '12GB',
                'processor' => 'Google Tensor G3',
                'performance' => 'High-end',
                'display' => '6.7-inch LTPO OLED 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'OnePlus',
                'model_name' => '12',
                'slug' => 'oneplus-12',
                'image_url' => 'https://images.unsplash.com/photo-1616423640778-28d1b53229bd?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5400mAh',
                'camera' => '50MP main + 48MP ultrawide + 64MP periscope',
                'storage' => '256GB / 512GB',
                'ram' => '12GB / 16GB',
                'processor' => 'Snapdragon 8 Gen 3',
                'performance' => 'Flagship',
                'display' => '6.82-inch LTPO AMOLED 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Oppo',
                'model_name' => 'Find X7 Ultra',
                'slug' => 'oppo-find-x7-ultra',
                'image_url' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5000mAh',
                'camera' => '50MP main + 50MP ultrawide + 50MP telephoto + 50MP periscope',
                'storage' => '256GB / 512GB / 1TB',
                'ram' => '12GB / 16GB',
                'processor' => 'Snapdragon 8 Gen 3',
                'performance' => 'Flagship',
                'display' => '6.82-inch LTPO AMOLED 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Vivo',
                'model_name' => 'X100 Pro',
                'slug' => 'vivo-x100-pro',
                'image_url' => 'https://images.unsplash.com/photo-1605236453921-7b1b6caa4f0d?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5400mAh',
                'camera' => '50MP main + 50MP ultrawide + 50MP telephoto',
                'storage' => '256GB / 512GB',
                'ram' => '12GB / 16GB',
                'processor' => 'Dimensity 9300',
                'performance' => 'Flagship',
                'display' => '6.78-inch LTPO AMOLED 120Hz',
                'operating_system' => 'Android 14',
            ],
            [
                'brand' => 'Nothing',
                'model_name' => 'Phone (2a)',
                'slug' => 'nothing-phone-2a',
                'image_url' => 'https://images.unsplash.com/photo-1598327105667-5b89351aff98?auto=format&fit=crop&w=900&q=80',
                'release_year' => 2024,
                'battery' => '5000mAh',
                'camera' => '50MP main + 50MP ultrawide',
                'storage' => '128GB / 256GB',
                'ram' => '8GB / 12GB',
                'processor' => 'Dimensity 7200 Pro',
                'performance' => 'Balanced',
                'display' => '6.7-inch AMOLED 120Hz',
                'operating_system' => 'Android 14',
            ],
        ];

        foreach ($devices as $device) {
            Device::updateOrCreate(
                ['slug' => $device['slug']],
                [
                    ...$device,
                    'specs' => [
                        'battery' => $device['battery'],
                        'camera' => $device['camera'],
                        'storage' => $device['storage'],
                        'ram' => $device['ram'],
                        'processor' => $device['processor'],
                        'performance' => $device['performance'],
                        'display' => $device['display'],
                        'operating_system' => $device['operating_system'],
                    ],
                    'is_active' => true,
                ]
            );
        }
    }
}
